version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-oras
    binary: '{{ .ProjectName }}_v{{ .Version }}'
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X github.com/vmvarela/terraform-provider-oras/internal/oras.Version={{ .Version }}'
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
    main: ./

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - id: checksum-sign
    artifacts: checksum
    ids:
      - checksum
    cmd: sh
    args:
      - "-c"
      - 'if [ -n "{{ .Env.GPG_FINGERPRINT }}" ]; then exec gpg --batch --local-user "{{ .Env.GPG_FINGERPRINT }}" --output "${signature}" --detach-sign "${artifact}"; fi'

release:
  draft: true
  prerelease: auto
  name_template: "v{{ .Version }}"

changelog:
  disable: true
